
spring.application.name=smartsplit

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

app.frontend-url=${FRONTEND_URL:http://localhost:3000}